[package]
name = "ethereum-forkid"
version = "1.0.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
repository = "https://github.com/vorot93/ethereum-forkid"
documentation = "https://docs.rs/ethereum-forkid"
description = "Ethereum fork identifier for chain compatibility checks"
keywords = ["ethereum"]
license = "MPL-2.0"
edition = "2024"

[dependencies]
crc = "1"
maplit = "1"
primitive-types = { version = "0.14", default-features = false }
fastrlp = { version = "0.4", features = ["derive"] }
thiserror = "2"

[dev-dependencies]
hex-literal = "1"
